### ISSUE TITLE
Interface flashing

### ISSUE THREAD

**Issue by looksoo** [tishion/QCefView#15]
Hi:
    Thank you for opening the code.
    I have problems using QCefView, When I  Change Windows operating system default font size， For example, zoom in 120% Or 150%,  The QCefViewTest program interface appears to be flashing;
    Run the Test examples in the CEF library, cefsimple.exe is Running normally;
    The environment is as follows:
     Qt 5.7.1 Win32  
     cef_binary_3.2623.1401.gb90a3be_windows32

**Comment by tishion** [comment]
@looksoo  Can you give a screenshot ? and you are using Windows 10, right?

**Comment by looksoo** [comment]
![1111](https://user-images.githubusercontent.com/1764588/29198655-8f43b72c-7e78-11e7-8a06-dc04f36175d9.jpg)
![2222](https://user-images.githubusercontent.com/1764588/29198663-a2ee692a-7e78-11e7-86a3-483b089c9149.jpg)
![333](https://user-images.githubusercontent.com/1764588/29198667-ac3534b4-7e78-11e7-9bd9-046ef3b1e414.jpg)
@tishion Yes, win10 , has the same problem in win 8.1

**Comment by tishion** [comment]
Hi @looksoo  thanks for your help.
I hvave confirmed and fixed this problem.  [Add DPI awareness for demo projects ](https://github.com/tishion/QCefView/commit/f230bdb4c484e0b372aa3515516ea3f173e10595)
This problem is not caused by QCefView. It's caused by the application manifest of windows application. If you want to add support for the High DPI awareness you need create and emend the correct manifest.

`
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3" >
  <asmv3:application>
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>true</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>
</assembly>
`

Or you could set this in visual studio:
![E.G.](https://i-msdn.sec.s-msft.com/dynimg/IC534217.png)


For more details:
[Writing DPI-Aware Desktop and Win32 Applications](https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266(v=vs.85).aspx)

**Comment by tishion** [comment]
related issue #13
