### ISSUE TITLE
Can you answer some questions for me?

### ISSUE THREAD

**Issue by 244986830** [tishion/QCefView#19]
1. Does the project depend on a specific version of CEF?
2. Does the project depend on a specific version of VS and Qt?
3. If I compile the CEF on VS2015,  can I compile this project on VS2013?
Thank you for your reply.

**Comment by zhulingbiezhi** [comment]
@244986830 The code compile always error, so I write the .pro file myself. I compile cef  and qcefview use vs2013

**Comment by looksoo** [comment]
@244986830  QcefView should be no limits ， CEF & QcefView use same compilation tool chain， The CEF has compiler limits；

**Comment by tishion** [comment]
@244986830  Let me answer your question in short words.
1. NO 2. NO 3. NO

Regarding to your first question: you can choose any version CEF as long as the APIs referred by this project exists in the CEF you chosen.

Regarding to the second one: You can choose any  version QT SDK as long as the QT classes referred by this project exists in the QT SDK you chosen.  If you have decided the version of the QT SDK you can choose whichever VS you wanted as long as you can get the corresponding version from official Qt website.


The last one question, no. You can not do that , because the final target file are not binary compatible due to the different toolset. For more detailed information please refer to: https://docs.microsoft.com/en-sg/cpp/porting/overview-of-potential-upgrade-issues-visual-cpp 

if you are not clear about my answer, please let me know and i can explain it in Chinese for you. : )

**Comment by 244986830** [comment]
Thank you very much! Then there was an error when I compiled the QCefView on VS2015 Release, but not on VS2015 Debug.
ERROR	C2027	undefined Type“QVariant”	QCefView	C:\Qt\Qt5.7.0\5.7\msvc2013\include\QtCore\qtypeinfo.h	67	C:\Qt\Qt5.7.0\5.7\msvc2013\include\QtCore\qtypeinfo.h	69	C:\Qt\Qt5.7.0\5.7\msvc2013\include\QtCore\qlist.h	458	C:\Qt\Qt5.7.0\5.7\msvc2013\include\QtCore\qlist.h	471	C:\Qt\Qt5.7.0\5.7\msvc2013\include\QtCore\qlist.h	477	

Can I compile it on VS2013?

**Comment by tishion** [comment]
@244986830  Please check you Qt SDK environment configuration.
QVariant is a class in Qt SDK

**Comment by lgxZJ** [comment]
@244986830  i meet the same problem, how did you resolve it?

**Comment by tishion** [comment]
@244986830 @lgxZJ   Sorry this is bug of missing some header files.
I have fixed this problem but not push the change yet.
I will push the fix this evening.

**Comment by tishion** [comment]
@244986830  @lgxZJ 
Fixed already #23
