### ISSUE TITLE
Wrong plugin settings (flash cannot be loaded correctly)

### ISSUE THREAD

**Issue by lgxZJ** [tishion/QCefView#24]
You plugin settings (class---QCefView::Implementation, line---39, code---browserSettings.plugins = STATE_DISABLED) was wrong, this prevents users from using other plugins. Maybe you could choose a more friendly way to control this.

**Comment by tishion** [comment]
Hi @lgxZJ, thank you for coming up this question, but this is by design initially. Because  this project is used to display some web content created by ourselves and we definitely don't need to load any plugins.

If you want to load plugins you can change this settings by yourself. This is why i provide source code rather than binary distribution.

**Comment by lgxZJ** [comment]
@tishion  got it, thanks for your explanations。
