### ISSUE TITLE
undefined CefGeolocationHandler

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [tishion/QCefView#35]
identifier "CefGeolocationHandler" is undefined	on file QCefViewBrowserHandler.h

**Comment by MrAhmedSayedAli** [comment]
[Remove geolocation API support (issue #2380)](https://github.com/chromiumembedded/cef/commit/ac86b611391b606170351bae322be1dd18d5a38b)

**Comment by tishion** [comment]
If you want to use the latest CEF then you need to give me some time to fix it.

**Comment by diegosousa88** [comment]
Hi @tishion 
Which is CEF's latest version compatible with QCefView?

**Comment by MrAhmedSayedAli** [comment]
i fix it by comment class CefGeolocationHandler; and Geolocation function 
and work fine

**Comment by diegosousa88** [comment]
Me too @MrAhmedSayedAli , but I cannot run QCefViewTest project sample code with the latest version of CEF (build 3.3325.1746.ge81cdf2). It crashes when calls cef_initialize in libcef_dll_wrapper as those images below show.

First occurs an exception telling that code triggers a breakpoint.
![breakpointtrigger](https://user-images.githubusercontent.com/4195319/37499634-88a46620-28a3-11e8-87f8-859c27521611.PNG)

When I try to continue it occurs an exception telling that an illegal instruction was executed.
![illegalinstruction](https://user-images.githubusercontent.com/4195319/37499633-88825184-28a3-11e8-8f28-cdaaa1d37c35.PNG)

Could you tell me which version of CEF are you using?

**Comment by tishion** [comment]
Sorry guys, it is work time now. I can only work on this in the weekend. I would like to add cef repo as a submodule of QCefView

**Comment by MrAhmedSayedAli** [comment]
@diegosousa88 
download http://opensource.spotify.com/cefbuilds/cef_binary_3.3325.1746.ge81cdf2_windows32.tar.bz2
or 64 if you want
use cmake to build ( MD  Build )

**Comment by diegosousa88** [comment]
Even downloading this version the issue persists for me. I'll continue to investigate why.
Thanks @MrAhmedSayedAli

**Comment by diegosousa88** [comment]
I think that I discovered the cause of triggered breakpoint exception mentioned above.
Actually this issue lies over `CCefSetting` constructor that considers `QDir::current()`  to find qtcefwing.exe (through CefSettings's `browser_sub_process_path` field), resources directory (through CefSettings's `resource_directory_path` field) and locales directory (through CefSettings's `locales_directory_path` field) in runtime.
`QDir::current` static member function returns application's current directory (more info in http://doc.qt.io/qt-5/qdir.html#current) that may change during runtime (I do not investigate yet what's changing application's current directory, maybe some CEF's code is doing that). So I changed this approach to use qApp macro (more info in http://doc.qt.io/qt-5/qapplication.html#qApp) so I can make sure that I'm looking for qtcefwing.exe, resources directory and locales directory in build's output folder.

Another thing that was necessary to make it work was add a post-build event to copy /dep/cef/resources/icudtl.dat to the same folder of libcef.dll file as was mentioned here in this CEF's forum thread below:
http://magpcss.org/ceforum/viewtopic.php?f=6&t=10977

Here's the QCefViewTest working with CEF version 3.3325.1746.ge81cdf2 using Chromium version 65.0.3325.146
![cefupgradeto3 3325 1746 ge81cdf2](https://user-images.githubusercontent.com/4195319/37789989-1148a5fa-2de4-11e8-9367-2eab8b776ae3.png)

**Comment by diegosousa88** [comment]
@tishion I tried to push a new branch called SupportToCEFVersion3.3325.1746.ge81cdf2 in this repo but seems that I'm not allowed to do that.
![pusherror](https://user-images.githubusercontent.com/4195319/37791335-ba18a786-2de7-11e8-88c7-08f7dd877686.png)

I'd like to share my discoveries in this repo in a separate branch and maybe merge (if you think that makes sense what I've done) with master branch, could you help me with that?

**Comment by tishion** [comment]
Hey guys, i am so busy now that i don't have time to work on any items except my work.. That's sad because i come back to China. My work takes all my time.
