### ISSUE TITLE
Visual Studio 2015 x64 prebuilt binaries

### ISSUE THREAD

**Issue by lindevs** [tishion/QCefView#8]
Hi. Can you built QCefView project binaries with **Visual Studio 2015 x64 Release, Multi-threaded DLL (/MD)**, because I get compiler errors. I can send prebuilt libcef_dll_wrapper.lib x64 (Multi-threaded DLL (/MD)). Thanks.

**Comment by tishion** [comment]
hi @lindevs what do you mean of **Visual Studio 2015 x64 prebuilt** ?  I remember there is no 64 bit version VS.

**Comment by lindevs** [comment]
I want that you compile your QCefView library and send to me .lib, .dll files :) (You can add prebuilt binaries in github release section). When I try to compile I get a lot off errors. So i need QCefView .lib and .dll compiled with VS2015 with settings x64 Release, Multi-threaded DLL (/MD). Thanks.

**Comment by tishion** [comment]
hi @lindevs , I am sorry, I will not do this for you. Because if you want to use 64 bit version QCefView you need to use 64 bit CEF and 64 bit Qt framework, so you need to build all the things by your self. I will make some change to QCefView to support  for multi architecture. But you still need to compile it by yourself.

I am sorry. Hope you can learn more about the CEF and QT. Thanks.
